# Note: if you modify this file, don't forget to update
# checksum in .drone.sec with:
# drone secure --repo webrtc/webrtc-org --checksum
clone:
  depth: 1
cache:
  mount:
    - vendor/bundle
build:
  image: ruby:2.0
  commands:
    - bundle install --deployment --jobs=3 --retry=3
    - bundle exec jekyll build --config _config.yml,_config_prod.yml
publish:
  # see http://addons.drone.io/google_cloud_storage/ for details
  gcs:
    when:
      repo: webrtc/webrtc-org
      branch: gh-pages
      event: push
    auth_key: >
      $$SERVICE_ACCOUNT_KEY
    source: _site
    target: weasel-webrtc
    cache_control: public,max-age=600
    gzip:
      - html
      - css
      - js
      - svg
